### ISSUE TITLE
suggestion to reduce file transfer

### ISSUE THREAD

**Issue by plaidman** [StevenMattera/SDFileUpdater#1]
Right now I see that the server packages up the whole repo to send it down to the switch, then the switch app unzips and picks out the folder for the launcher that it wants.

I think it might be beneficial to include the launcher string in the server URL, then do the logic for picking out which launcher version on the server side in the .js files. This will have three benefits:

1) The .zip that the switch is retrieving will be much smaller, since you're not packaging up three (or more later) launcher versions.
2) The logic on the switch app will be much simpler - just unzip and overwrite.
3) The server, which is arguably much easier to modify for someone who is running their own, can be extended and cusomized to pull from anywhere as long as it responds with a zip of the exact file structure that will be written to the SD card.

**Comment by StevenMattera** [comment]
Funny enough I just saw this and was already implementing this. I realized it last night as I was going to sleep. The new server code has already been pushed to it's repository and is live on my server. Thanks for the suggestion! I should have an update here shortly to the app.

**Comment by plaidman** [comment]
Awesome! Can't wait to hook this up to my own repo!
